/**
 * SHA-256 of `public/backup-viewer.html`, regenerated by
 * `scripts/build-backup-viewer.mjs` as the FIRST step of `npm run build`.
 *
 * The app compiles this in and checks the file it hands the user against it
 * (D19). That closes the DELIVERY channel — a download corrupted or swapped in
 * transit — and nothing more: an attacker who can rewrite the saved file can
 * rewrite a checksum stored beside it just as easily. Authenticity therefore
 * rests on the user keeping this value somewhere independent, and the app says
 * so in as many words.
 *
 * DO NOT EDIT BY HAND.
 */
export const BACKUP_VIEWER_SHA256 = 'not-built-yet';

/** True when the constant above is the placeholder from a clean checkout
 *  rather than a real build output. Consumers must refuse to present the
 *  download as verified while this holds. */
export const BACKUP_VIEWER_HASH_IS_PLACEHOLDER = true;
