/**
 * Post-build patcher. Runs after `vite build`.
 *
 * Writes dist/_headers with a strict CSP whose connect-src is pinned to the
 * validated VITE_PROXY_URL origin (only its .origin; non-localhost must be
 * https; empty/invalid fails the build).
 *
 * The service worker + manifest are generated by vite-plugin-pwa (Phase 8) —
 * no BASE/BUILD_HASH patching needed anymore; base flows through Vite.
 *
 * Default base is '/' (Cloudflare Pages). The GitHub Pages target that needed
 * '/payee/' is retired and unpublished (2026-08-20).
 */
import { writeFileSync } from 'node:fs';
import { resolveProxyOrigin } from './proxy-origin.mjs';

const base = process.env.VITE_BASE || '/';
const rawProxy = process.env.VITE_PROXY_URL || '';

let origin;
try {
  origin = resolveProxyOrigin(rawProxy, {
    // Any CI marker means "this artifact may ship" → http://localhost is banned
    // there even though it stays convenient for local dev builds.
    ci: process.env.CI === 'true' || process.env.CI === '1' || !!process.env.GITHUB_ACTIONS,
    allowHttp: process.env.ALLOW_HTTP_PROXY === '1',
  });
} catch (e) {
  throw new Error(`postbuild: invalid VITE_PROXY_URL "${rawProxy}": ${e.message}`);
}

/**
 * The standalone viewer carries its OWN hash-based CSP in a <meta> tag, and it
 * must be the only policy in force.
 *
 * The leading `!` is not decoration: Cloudflare Pages INHERITS matched rules
 * and COMBINES same-named values, so without an explicit unset the site policy
 * above would be concatenated with the page's meta. Two policies are enforced
 * as their INTERSECTION, and the site policy has no `sha256-` allowance for
 * the viewer's inlined script — the page would silently fail to run, offline,
 * in the exact situation it exists for.
 *
 * Both paths are listed: the extensionless canonical route (served through a
 * 200 rewrite) and the file itself, which stays directly reachable.
 */
const VIEWER_HEADERS = ['/backup-viewer', '/backup-viewer.html']
  .map(path => `${path}
  ! Content-Security-Policy
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: no-referrer
`)
  .join('\n');

// ── Write _headers with CSP ──
// (sw.js + manifest.webmanifest are fully generated by vite-plugin-pwa)
const csp = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'", // wasm-unsafe-eval: Argon2 (hash-wasm)
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src 'self' https://arweave.net ${origin}`,
  "worker-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
].join('; ');

writeFileSync('dist/_headers', `/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()

/assets/*
  Cache-Control: public, max-age=31536000, immutable

${VIEWER_HEADERS}`);

// SW versioning is content-hash based (Workbox revisions) — no SHA stamping.
console.log(`postbuild: base=${base} connect-src proxy=${origin}`);
