/**
 * Post-build patcher. Runs after `vite build`.
 *
 * Writes dist/_headers with a strict CSP whose connect-src is pinned to the
 * validated VITE_PROXY_URL origin (only its .origin; non-localhost must be
 * https; empty/invalid fails the build).
 *
 * The service worker + manifest are generated by vite-plugin-pwa (Phase 8) —
 * no BASE/BUILD_HASH patching needed anymore; base flows through Vite.
 *
 * Default base is '/' (Cloudflare Pages). The GitHub Pages target that needed
 * '/payee/' is retired and unpublished (2026-08-20).
 */
import { writeFileSync } from 'node:fs';
import { resolveProxyOrigin } from './proxy-origin.mjs';
import { cspConnectOrigins } from './gateways-parse.mjs';

const base = process.env.VITE_BASE || '/';
const rawProxy = process.env.VITE_PROXY_URL || '';

// connect-src is generated from the SAME lists the client compiles in (D8), so
// a gateway the runtime would call can never be one the policy forbids. Index
// entries contribute their origin only — connect-src is origin-scoped.
// The empty-env default mirrors src/lib/gateways.ts: a lone arweave.net.
const gatewayOrigins = cspConnectOrigins({
  status: process.env.VITE_STATUS_GATEWAYS,
  payload: process.env.VITE_PAYLOAD_GATEWAYS,
  indexSources: process.env.VITE_INDEX_SOURCES,
});
const connectOrigins = gatewayOrigins.length > 0 ? gatewayOrigins : ['https://arweave.net'];

let origin;
try {
  origin = resolveProxyOrigin(rawProxy, {
    // Any CI marker means "this artifact may ship" → http://localhost is banned
    // there even though it stays convenient for local dev builds.
    ci: process.env.CI === 'true' || process.env.CI === '1' || !!process.env.GITHUB_ACTIONS,
    allowHttp: process.env.ALLOW_HTTP_PROXY === '1',
  });
} catch (e) {
  throw new Error(`postbuild: invalid VITE_PROXY_URL "${rawProxy}": ${e.message}`);
}

// ── Write _headers with CSP ──
// (sw.js + manifest.webmanifest are fully generated by vite-plugin-pwa)
const csp = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'", // wasm-unsafe-eval: Argon2 (hash-wasm)
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src 'self' ${connectOrigins.join(' ')} ${origin}`,
  "worker-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
].join('; ');

writeFileSync('dist/_headers', `/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()

/assets/*
  Cache-Control: public, max-age=31536000, immutable
`);

// SW versioning is content-hash based (Workbox revisions) — no SHA stamping.
console.log(
  `postbuild: base=${base} connect-src proxy=${origin} ` +
    `gateways=${connectOrigins.length} (${connectOrigins.join(',')})`,
);
